version: "3.7"

services:
    app:
        build: .
        container_name: rentx
        ports:
            - 3333:3333
        volumes: 
            - .:/usr/app
        restart: always
        depends_on:
            - database_ignite

    database_ignite:
        image: postgres
        container_name: database_ignite
        restart: always
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/data/postgres
 

volumes:
    pgdata:
        driver: local
